global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'devsecops-app'
    static_configs:
      - targets: ['devsecops-app:80']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    metrics_path: '/api/system/status'
    scrape_interval: 60s

  - job_name: 'reports-server'
    static_configs:
      - targets: ['reports-server:80']
    metrics_path: '/health'
    scrape_interval: 30s